### ISSUE TITLE
cmake fails on macos 13

### ISSUE THREAD

**Issue by fractalshine** [Swartz27/xray-16#1135]
**Describe the bug**
When i'm trying to cmake happen this error

```
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**To Reproduce**
cmake in bin directory

**Expected behavior**
cmake w/o errors

**Desktop (please complete the following information):**
 - OS: macos ventura 13.0.1
 - MBP M1, 16GB RAM
 - clang version: Apple clang version 14.0.0 (clang-1400.0.29.202)
 - OpenXRay build version 
 -  git commit: 96797aa25cbad2f296b2684c6ecf4641a690be65
 -  git branch: dev

**Comment by Xottab-DUTY** [comment]
@Lnd-stoL, @vertver, maybe you guys know something how this can be fixed?

**Comment by fractalshine** [comment]
As "workaround" i've used MacOSX11.3.sdk from [here](https://github.com/phracker/MacOSX-SDKs)

**Comment by pkolchanov** [comment]
I've set `SDKROOT` manually. This resolves the issue with `TargetConditionals.h`. 

`export SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"`

**Comment by johncurley** [comment]
I tried all sorts of things in the CMAKE files and the only thing I can get to work is either @pkolchanov 's solution above or `export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"` which is a cleaner solution but pretty much the same thing as above. I don't think there's any other way to get the script to find the sdk.

**Comment by johncurley** [comment]
This problem doesn't appear during command line build or on other IDE's except when building Xcode project files from cmake so I assume it's something to do with Luajit and is external to the project. I tried setting https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_SYSROOT.html but it wouldn't work as the environmental variable would not carry over to Luajit's build files. We know the environment can find the path otherwise export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)" wouldn't work. I really can't think of any simple solution except to rewrite the Luajit build scripts but I don't think that's a good idea and probably best to leave everything alone and just set export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)" manually.
