### ISSUE TITLE
-draw_borders does nothing

### ISSUE THREAD

**Issue by Hezkore** [Swartz27/xray-16#1714]
**Describe the bug**
The -draw_borders launch command does nothing.

**To Reproduce**
1. Read Wiki and see -draw_borders
2. Launch with -draw_borders
3. See borderless window

**Expected behavior**
See bordered window.

**Desktop (please complete the following information):**
 - OS: Win11
 - OpenXRay build: Stable

**Comment by Xottab-DUTY** [comment]
The issue here is that the game window doesn't automatically change it's position on the screen accordingly with the option.
The borders are there, but they are outside of the screen.
You need to move the game window manually: in the main menu press Alt+Win, then press LMB on the window and drag it.

For now, I don't think I'm going to fix this somehow. I believe it's SDL2 fault. (SDL2 is a library that we use under the hood)

P.S. also, what OpenXRay stable build means? Is it 2020 or 2021 release?
Just FYI – `-draw_borders` was removed somewhere in 2023 and replaced with a new `vid_window_mode` console command and an option in the in-game video settings.
