### ISSUE TITLE
Unhandled dependency d3dcompiler_47.dll

### ISSUE THREAD

**Issue by flossy83** [Swartz27/xray-16#914]
I am using the Steam version of CoP which I have modded to OpenXRay according to the instructions in this Git.

When launching Stalker-COP.exe I get the error "d3dcompiler_47.dll is missing".   I can click OK and the game loads, but DX10/11 renderer options are missing.

I downloaded all DirectX end-user runtimes that I could find at Microsoft.com to no effect.

I searched for the file on my computer and found it exclusively in C:\Program Files (x86)\Steam\bin\cef\cef.win7x64\d3dcompiler_47.dll

Copying it to the game's folder resolves the issue.

![d3d9compiler_47](https://user-images.githubusercontent.com/46382337/143134798-d9c1724a-d426-4839-8d64-ae0b3c0addd1.png)

**Comment by Xottab-DUTY** [comment]
Can you tell what version of OpenXRay you are using and your OS version, please?

**Comment by flossy83** [comment]
> Can you tell what version of OpenXRay you are using and your OS version, please?

The latest one in this repository (xray-16).  OS is Win7 x64 Ultimate SP1.

**Comment by Xottab-DUTY** [comment]
The latest release, which is December 2020 Preview, or the latest development build?

**Comment by flossy83** [comment]
I downloaded the latest one from the releases section of this Git.  It appears that is the Dec 2020 Preview.

**Comment by Xottab-DUTY** [comment]
I will try to fix this for the new release.

**Comment by Xottab-DUTY** [comment]
Task:
- [x] Redistribute d3dcompiler_47.dll with our binaries. (deb16c2f6942457e26acac0e8eb3901c5c75494d)
- [x] Do something with error window. May be hide it as it was being hidden in vanilla engine or guarantee that it will never be shown. (including if other `d3d*` DLLs are missing)
    - Should not appear after deb16c2f6942457e26acac0e8eb3901c5c75494d, I think.

Notes:
- https://walbourn.github.io/hlsl-fxc-and-d3dcompile/
- https://walbourn.github.io/whats-up-with-d3dcompiler_xx-dll/
- https://walbourn.github.io/twilight-for-windows-7/
- d3dcompiler_43.dll is distributed with our binaries, but not used. (we may want to look at it when solving #101)
  - It's not used because renderer should use `D3D*` functions instead of `D3DX*`. (for example, we need to use `D3DCompile` instead of `D3DXCompileFromMemory`)
    - We can't use newer compiler, because of shader compilation errors.
- https://docs.microsoft.com/en-us/windows/win32/directx-sdk--august-2009-?redirectedfrom=MSDN
- https://stackoverflow.com/questions/27084865/can-a-directx-executable-be-statically-linked-such-that-the-redistributable-dll
- https://docs.microsoft.com/en-us/windows/win32/direct3darticles/direct3d11-deployment?redirectedfrom=MSDN

**Comment by flossy83** [comment]
Today I installed .NET Framework 4.8 and that allowed me to remove d3dcompiler_47.dll from the game folder.   This appears due to the .NET 4.8 installer adding d3dcompiler_47.dll to windows\system32 folder.

**Comment by Roman-n** [comment]
Xottab-DUTY and did you have before with d3dcompiler_47.dll have you had any problems? We had it on OXR_CoC right away.
And yes - it has something to do with .NET Framework 4.8, and we have an installation recommendation.NET Framework 4.8 - but not all players can install it on their OS - that's why not everyone can run the game...

**Comment by Xottab-DUTY** [comment]
> Xottab-DUTY and did you have before with d3dcompiler_47.dll have you had any problems?

I wasn't aware of this problem)

> And yes - it has something to do with .NET Framework 4.8, and we have an installation recommendation.NET Framework 4.8 - but not all players can install it on their OS - that's why not everyone can run the game...

It has nothing to do with .NET Framework. Its installer *probably* just adds .NET files to the global search path and d3dcompiler also appears there by accident.

The correct way is to ask user to install DirectX redistributables ([installer link](https://www.microsoft.com/en-us/download/details.aspx?id=35)), integrate DirectX installer into your installer ([link with some help about how to do that](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/direct3d11-deployment)) or distribute them yourself with the engine as I just did in deb16c2f6942457e26acac0e8eb3901c5c75494d. :)
*(not all binaries are allowed to be distributed by Microsoft licence, but, for instance, d3dcompiler is allowed)*
